apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata-sit
  namespace: common-server
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-common-data