version: '3'
services:
  kafka:
    image: registry.cn-shenzhen.aliyuncs.com/sdtc/kafka:2.12-2.4.1
    restart: always
    container_name: kafka
    ports:
      - 9092:9092
    volumes:
      - /etc/hosts:/etc/hosts
      - /data/kafka/data:/kafka:rw
    environment:
      KAFKA_BROKER_ID: "0" 
      KAFKA_ZOOKEEPER_CONNECT: "192.168.3.42:2181" 
      KAFKA_ADVERTISED_HOST_NAME: "192.168.3.43" 
      KAFKA_ADVERTISED_PORT: "9092" 
      KAFKA_HEAP_OPTS: "-Xmx4G -Xms4G"