version: "3.2"
services:
  elasticsearch:
    image: registry.cn-shenzhen.aliyuncs.com/4d_prom/elasticsearch:7.12.1 
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      discovery.type: "single-node" 
    volumes:
      - /data/es/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
      - /data/es/data/:/usr/share/elasticsearch/data:rw
      - /data/es/logs/:/usr/share/elasticsearch/logs:rw      
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: registry.cn-shenzhen.aliyuncs.com/4d_prom/kibana:7.12.1
    container_name: kibana
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    networks:
      - elk 
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge