version: "3.2"
services:
  elasticsearch:
    image: registry.cn-shenzhen.aliyuncs.com/sdtc/elasticsearch:6.8.0
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      discovery.type: "single-node" 
    volumes:
      - /data/es/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml 
      - /data/es/data/:/usr/share/elasticsearch/data:rw
      - /data/es/logs/:/usr/share/elasticsearch/logs:rw
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: registry.cn-shenzhen.aliyuncs.com/sdtc/kibana:6.8.0
    container_name: kibana
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    networks:
      - elk 
    depends_on:
      - elasticsearch

  logstash:
      image: registry.cn-shenzhen.aliyuncs.com/sdtc/logstash:6.8.0.1
      container_name: logstash
      hostname: logstash
      restart: always
      volumes:
        - /data/logstash/conf/:/opt/kibana/config/ 
      ports:
        - 9600:9600
        - 5044:5044
      networks:
        - elk
      depends_on:
        - elasticsearch

networks:
  elk:
    driver: bridge