apiVersion: v1
kind: Endpoints
metadata:
  name: rocketmq
  namespace: dev
subsets:
- addresses:
  - ip: 192.168.21.2
  ports:
  - port: 6379
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: rocketmq
spec:
  ports:
    - port: 6379
      targetPort: 26379


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetDnsRecordIds: '["common-server:mqnamesrv-dev"]'
    field.cattle.io/targetWorkloadIds: "null"
  labels:
    cattle.io/creator: norman
  name: rocketmq
  namespace: dev
spec:
  clusterIP: None
  sessionAffinity: None
  type: ClusterIP