apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-exporter
  name: redis-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
      - args:
        - --redis.addr=r-wz9bdc783e847b54.redis.rds.aliyuncs.com:6379
        - --redis.password="liuqian77!"
        name: redis-exporter
        image: oliver006/redis_exporter
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: 4dtc          
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    app: redis-exporter
spec:
  ports:
  - name: port-tcp-9121
    port: 9121
    targetPort: 9121  
  selector:
    app: redis-exporter
  type: ClusterIP