apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sit
  namespace: common-server
  labels:
    app: redis-sit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sit
  template:
    metadata:
      labels:
        app: redis-sit
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - service    
      # 进行初始化操作，修改系统配置，解决 Redis 启动时提示的警告信息
      initContainers:
        - name: system-init
          image: busybox:1.32
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "echo 2048 > /proc/sys/net/core/somaxconn && echo never > /sys/kernel/mm/transparent_hugepage/enabled"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
          - name: sys
            mountPath: /sys
      containers:
        - name: redis-sit
          image: registry.cn-shenzhen.aliyuncs.com/4d_prom/redis:6.2.5
          command:
            - "sh"
            - "-c"
            - "redis-server /etc/redis/redis.conf"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 300
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
      tolerations:
      - effect: NoSchedule
        key: role
        operator: Equal
        value: service                
      volumes:
        - name: data
          hostPath:
            path: /logs/common/sit/redis
        - name: config
          configMap:
            name: redis-sit-config
        - name: sys
          hostPath:
            path: /sys
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sit
  namespace: common-server
  labels:
    app: redis-sit
spec:
  ports:
  - name: port-tcp
    port: 6379
    nodePort: 26379
  selector:
    app: redis-sit
  type: NodePort     
