kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-sit-config
  namespace: common-server
  labels:
    app: redis-sit
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    protected-mode no
    dbfilename dump.rdb
    pidfile /data/redis-6379.pid