apiVersion: v1
kind: Endpoints
metadata:
  name: redis
  namespace: dev
subsets:
- addresses:
  - ip: 192.168.21.2
  ports:
  - port: 6379
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 26379