---
- name: "create node user"
  hosts: all
  become: yes
  become_user: root
  
  vars:
    sshd_config_path: /etc/ssh/sshd_config
  tasks:
  - name: Add user {{ user_add }}
    user: name={{user_add}} comment="ceph user" password='$6$a30rK6VABh.OySpE$d4.jGbwaSAnM2rdLflkdBIdJRsFIS6gAcAVm2z18qvBnEbVRMxvYwZlIYohLHcbGEqFo2QvUGG1uG46oa9NcT0'

  - name: Config /etc/sudoers
    lineinfile: dest=/etc/sudoers state=present  line='{{item}}' validate='visudo -cf %s'
    with_items:
      - "{{ user_add}} ALL=(ALL) NOPASSWD: ALL"
  - name: deploy ssh key
    authorized_key: user={{ user_add}}
                    key="{{ lookup('file', '/home/{{ user_add}}/.ssh/{{ pubkey }}.pub') }}"
                    state=present    
  # 开启 PubkeyAuthentication               
  - name: Open PubkeyAuthentication...
    lineinfile:
      dest: "{{sshd_config_path}}"
      regexp: "^PubkeyAuthentication"
      line: "PubkeyAuthentication yes"
  # 开启 关闭DNS缓存               
  - name: Close UseDNS...
    lineinfile:
      dest: "{{sshd_config_path}}"
      regexp: "^UseDNS"
      line: "UseDNS no"
  ## 关闭密码登陆通道                  
  #- name: Close PasswordAuthentication...
  #  lineinfile:
  #    dest: "{{sshd_config_path}}"
  #    regexp: "^PasswordAuthentication"
  #    line: "PasswordAuthentication no"
  # 重启sshd    
  - name: restart sshd...
    service: name=sshd state=restarted
    ignore_errors: yes                    



UseDNS yes

PubkeyAuthentication yes