---
- name: "docker install"
  hosts: all
  become: yes
  become_user: root

  tasks:
  - name: remove old docker
    yum:
      name: docker-ce.x86_64,docker-ce-cli.x86_64
      state: removed
    tags: docker-ce
  - name: download docker repo
    shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    tags: docker-ce  
  - name: Install docker-ce-{{ docker_version }},docker-ce-cli-{{ docker_version }} by yum 
    yum:
      name: "{{ packages }}" 
      state: present
    vars:
      packages:
      - docker-ce-{{ docker_version }}
      - docker-ce-cli-{{ docker_version }}
      - containerd.io
    tags: docker-ce         
  - name: Create Docker config directory. 
    file: path=/etc/docker state=directory 
  - name: Create Docker running data directory. 
    file: path=/data/docker/data state=directory             
  - name: Configure docker startup parameters.
    template:
      src: ../genconf/daemon.json
      dest: "/etc/docker/daemon.json"  
  - name: docker run for winbull
    shell: usermod -a -G docker winbull
  - name: startup docker
    service:
      name: docker
      state: started
      enabled: yes
    tags: docker-ce
  # 安装docker-compose 不需要可去掉  
  #- name: Ensure docker-compose is installed and available
  #  copy:
  #    src: "{{item.src}}"
  #    dest: "{{item.dest}}"
  #    mode: 0755
  #  with_items:
  #    - { src: "/opt/bin/docker-compose",dest: "/usr/local/bin/" }