version: '3.5'
services:
  rmqnamesrv:
    image: registry.cn-shenzhen.aliyuncs.com/sdtc/rocketmq:4.4.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - /data/rmqnamesrv/logs:/var/app/logs:rw
    environment:
      JAVA_OPT_EXT: "-server -Xms2g -Xmx2g -Xmn2g"
      JAVA_OPTS: " -Duser.home=/opt"
      MAX_POSSIBLE_HEAP: "200000000"  
    command: sh mqnamesrv 
    networks:
        rmq:
          aliases:
            - rmqnamesrv

  rmqbroker:
    image: registry.cn-shenzhen.aliyuncs.com/sdtc/rocketmq:4.4.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - /data/rmqbroker/logs:/var/app/logs
      - /data/rmqbroker/conf/broker.properties:/etc/rocketmq/broker.properties  

    command: sh mqbroker -c /etc/rocketmq/broker.properties   
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqbroker

  rmqconsole:
    image: registry.cn-shenzhen.aliyuncs.com/sdtc/rocketmq-console:1.0
    container_name: rmqconsole
    ports:
      - 8080:8080
    environment:
        JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqconsole

networks:
  rmq:
    name: rmq
    driver: bridge
