apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: loki
data:
  promtail-config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0  
    positions:
      filename: var/log/positions.yaml
    client:
      backoff_config:
        max_period: 5m
        max_retries: 10
        min_period: 500ms
      batchsize: 1048576
      batchwait: 1s
      external_labels: {}
      timeout: 10s      
    target_config:
      sync_period: 10s
    scrape_configs:



---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: loki
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: loki
          image: grafana/promtail:2.1.0
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/mnt/config/promtail-config.yml
            - -client.url=http://loki:3100/loki/api/v1/push
            - -client.external-labels=hostname=$(NODE_NAME)
          ports:
            - containerPort: 9080
          volumeMounts:
            - mountPath: /data/k8s/docker/data/containers
              name: containers-volume
            - mountPath: /var/log/pods
              name: pods-volume
            - mountPath: /mnt/config
              name: config-volume
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: containers-volume
          hostPath:
            path: /data/k8s/docker/data/containers
        - name: pods-volume
          hostPath:
            path: /var/log/pods
        - name: config-volume
          configMap:
            name: promtail-config
            items:
              - key: promtail-config.yml
                path: promtail-config.yml
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: promtail
  name: promtail
  namespace: loki
spec:
  ports:
  - name: http
    port: 9080
    nodePort: 31008
  selector:
    app: promtail
  type: NodePort          
