---
- name: etcd deploy
  hosts: all
  become: yes
  become_user: root
  vars:
    file_path: /opt/kubernetes
    system_path: /etc/systemd/system

  tasks:
  #TODO: 创建文件目录
  - name: Create bin dir
    file: path=/data/kubernetes/etcd/data state=directory recurse=yes  
  - name: Create ssl dir
    file: path=/data/kubernetes/etcd/wal state=directory recurse=yes
  - name: copy etcd bin
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    with_items:
      - { src: "{{file_path}}/bin/etcd",dest: "{{file_path}}/bin/" }
      - { src: "{{file_path}}/bin/etcdctl",dest: "{{file_path}}/bin/" }
  - name: copy ssl && cfg && services
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    with_items:
      - { src: "{{file_path}}/ssl/etcd.pem",dest: "{{file_path}}/ssl/etcd.pem" } 
      - { src: "{{file_path}}/ssl/etcd-key.pem",dest: "{{file_path}}/ssl/etcd-key.pem" } 
      - { src: "{{file_path}}/ssl/ca.pem",dest: "{{file_path}}/ssl/ca.pem" } 
      - { src: "{{file_path}}/cfg/etcd0{{n}}.service",dest: "{{system_path}}/etcd.service" }
  - name: startup etcd
    service:
      name: etcd
      state: started
      daemon_reload: yes
      enabled: yes    
    ignore_errors: yes         
