---
- name: etcd deploy
  hosts: all
  become: yes
  become_user: root
  vars:
    file_path: /opt/kubernetes
    system_path: /lib/systemd/system

  tasks:
  - name: copy etcd bin
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    with_items:
      - { src: "{{file_path}}/bin/etcd",dest: "{{file_path}}/bin/" }
      - { src: "{{file_path}}/bin/etcdctl",dest: "{{file_path}}/bin/" }
  - name: copy ssl and cfs
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    with_items:
      - { src: "{{file_path}}/ssl/etcd.pem",dest: "{{file_path}}/ssl/etcd.pem" } 
      - { src: "{{file_path}}/ssl/etcd-key.pem",dest: "{{file_path}}/ssl/etcd-key.pem" } 
      - { src: "{{file_path}}/ssl/ca.pem",dest: "{{file_path}}/ssl/ca.pem" } 
      - { src: "{{file_path}}/cfg/etcd0{{etcd_n}}",dest: "{{file_path}}/cfg/etcd" }  
  - name: cp etcd.service
    copy:
      src: "/home/admin/k8s-deploy/cluster/server/etcd.service"
      dest: "/lib/systemd/system/etcd.service"
  - name: startup etcd
    service:
      name: etcd
      state: started
      daemon_reload: yes
      enabled: yes               
