---
- name: kube-controller-manager  deploy
  hosts: all
  become: yes
  become_user: root
  vars:
    file_path: /opt/kubernetes
    system_path: /etc/systemd/system

  tasks:
  - name: copy ssl && cfg && services
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    with_items:
      - { src: "{{file_path}}/ssl/kube-controller-manager.pem",dest: "{{file_path}}/ssl/kube-controller-manager.pem" }
      - { src: "{{file_path}}/ssl/kube-controller-manager-key.pem",dest: "{{file_path}}/ssl/kube-controller-manager-key.pem" }
      - { src: "{{file_path}}/ssl/kube-controller-manager.kubeconfig",dest: "{{file_path}}/cfg/kube-controller-manager.kubeconfig" }
      - { src: "{{file_path}}/cfg/kube-controller-manager/kube-controller-manager0{{n}}.service",dest: "{{system_path}}/kube-controller-manager.service" }
  #TODO: 创建目录
  - name: Create kube-controller-manager dir
    file: path={{K8S_DIR}}/kube-controller-manager state=directory recurse=yes   
  
  - name: startup kube-controller-manager
    service:
      name: kube-controller-manager
      state: started
      daemon_reload: yes
      enabled: yes               
