---
- name: kubelet deploy
  hosts: all
  become: yes
  become_user: root
  vars:
    file_path: /opt/kubernetes
    system_path: /etc/systemd/system

  tasks:
  - name: Create kubelet logs dir
    file: path=/data/kubernetes/kubelet state=directory recurse=yes   
  - name: copy kubelet bin
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    with_items:
      - { src: "{{file_path}}/bin/kubelet",dest: "{{file_path}}/bin/" }
  - name: copy ssl && cfg && services
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    with_items:
      - { src: "{{file_path}}/ssl/ca.pem",dest: "{{file_path}}/ssl/ca.pem" } 
      - { src: "{{file_path}}/cfg/kubelet/kubelet-bootstrap-slave0{{n}}.kubeconfig",dest: "{{file_path}}/cfg/kubelet-bootstrap.kubeconfig" } 
      - { src: "{{file_path}}/cfg/kubelet/kubelet-config0{{n}}.yaml",dest: "{{file_path}}/cfg/kubelet-config.yaml" } 
      - { src: "{{file_path}}/cfg/kubelet/kubelet0{{n}}.service",dest: "{{system_path}}/kubelet.service" } 
  - name: startup kubelet
    service:
      name: kubelet
      state: started
      daemon_reload: yes
      enabled: yes               
