---
- name: kube-nginx deploy
  hosts: all
  become: yes
  become_user: root
  vars:
    file_path: /opt/kubernetes
    system_path: /etc/systemd/system

  tasks:
  #TODO: 创建kube-nginx文件目录
  - name: Create bin dir
    file: path={{file_path}}/kube-nginx/bin state=directory recurse=yes  
  - name: Create ssl dir
    file: path={{file_path}}/kube-nginx/cfg state=directory recurse=yes
  - name: Create cfg dir
    file: path={{file_path}}/kube-nginx/logs state=directory recurse=yes   
  - name: copy kube-nginx bin
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
      mode: 0755
    with_items:
      - { src: "{{file_path}}/bin/kube-nginx",dest: "{{file_path}}/kube-nginx/bin/" }
  - name: copy cfg && services
    copy:
      src: "{{item.src}}"
      dest: "{{item.dest}}"
    with_items:
      - { src: "{{file_path}}/kube-nginx/cfg/kube-nginx.conf",dest: "{{file_path}}/cfg/kube-nginx.conf" }  
      - { src: "/home/admin/k8s-deploy/cluster/server/kube-nginx.service",dest: "{{system_path}}/kube-nginx.service" }  
  - name: startup kube-nginx
    service:
    service:
      name: kube-nginx
      state: started
      daemon_reload: yes
      enabled: yes