---
- name: remove kubernetes master
  hosts: all
  become: yes
  become_user: root
  vars:
    file_path: /opt/kubernetes
    system_path: /lib/systemd/system

  tasks:     
  - name: Stop service kube-scheduler
    service:
      name: kube-scheduler
      state: stopped
  - name: Stop service kube-controller-manager
    service:
      name: kube-controller-manager
      state: stopped
  - name: Stop service kube-nginx
    service:
      name: kube-nginx
      state: stopped
  - name: Stop service kube-apiserver
    service:
      name: kube-apiserver
      state: stopped  
  - name: Stop service etcd
    service:
      name: etcd
      state: stopped                       
  - name: delete service
    file:
      path: "{{ item }}"
      state: absent  
    with_items:
      - /lib/systemd/system/kube-scheduler.service 
      - /lib/systemd/system/kube-controller-manager.service 
      - /lib/systemd/system/kube-nginx.service 
      - /lib/systemd/system/kube-apiserver.service 
      - /lib/systemd/system/etcd.service    
  - name: delete ssl path
    file:
      path: /opt/kubernetes/ssl
      state: absent
  - name: create ssl path    
    file:    
      path: /opt/kubernetes/ssl
      state: directory 
  - name: delete cfg path
    file:
      path: /opt/kubernetes/cfg
      state: absent
  - name: create cfg path    
    file:    
      path: /opt/kubernetes/cfg
      state: directory 
  - name: delete etcd path
    file:
      path: /data/k8s/etcd
      state: absent
  - name: create etcd path    
    file:    
      path: /data/k8s/etcd
      state: directory                                        
