---
- name: remove kubernetes master
  hosts: all
  become: yes
  become_user: root
  vars:
    file_path: /opt/kubernetes
    system_path: /lib/systemd/system

  tasks:
  - name: Stop service kube-proxy
    service:
      name: kube-proxy
      state: stopped
  - name: Stop service flanneld
    service:
      name: flanneld
      state: stopped  
  - name: Stop service kubelet
    service:
      name: kubelet
      state: stopped           
  - name: Stop service kube-scheduler
    service:
      name: kube-scheduler
      state: stopped
  - name: Stop service kube-controller-manager
    service:
      name: kube-controller-manager
      state: stopped
  - name: Stop service kube-nginx
    service:
      name: kube-nginx
      state: stopped
  - name: Stop service kube-apiserver
    service:
      name: kube-apiserver
      state: stopped  
  - name: Stop service etcd
    service:
      name: etcd
      state: stopped                       
  - name: delete service
    file:
      path: "{{ item }}"
      state: absent  
    with_items:
      - /lib/systemd/system/kube-proxy.service 
      - /lib/systemd/system/flanneld.service 
      - /etc/systemd/system/docker.service.requires/flanneld.service  
      - /lib/systemd/system/kubelet.service    
      - /lib/systemd/system/kube-scheduler.service 
      - /lib/systemd/system/kube-controller-manager.service 
      - /lib/systemd/system/kube-nginx.service 
      - /lib/systemd/system/kube-apiserver.service 
      - /lib/systemd/system/etcd.service   
  - name: delete k8s path
    file:
      path: "{{ item }}"
      state: absent  
    with_items:     
      - /opt/kubernetes/ssl
      - /opt/kubernetes/cfg
      - /data/k8s/etcd
      - /data/k8s/kube-apiserver
      - /data/k8s/kube-controller-manager
      - /data/k8s/kubelet
      - /data/k8s/kube-proxy
      - /data/k8s/kube-scheduler
  - name: create ssl path    
    file:    
      path: /opt/kubernetes/ssl
      state: directory 
  - name: create cfg path    
    file:    
      path: /opt/kubernetes/cfg
      state: directory 
  - name: create etcd path    
    file:    
      path: /data/k8s/etcd
      state: directory                                        
