---
- name: remove kubernetes node
  hosts: all
  become: yes
  become_user: root
  vars:
    file_path: /opt/kubernetes
    system_path: /lib/systemd/system

  tasks:     
  - name: Stop service kubelet
    service:
      name: kubelet
      state: stopped
  - name: Stop service kube-proxy
    service:
      name: kube-proxy
      state: stopped
  - name: Stop service flanneld
    service:
      name: flanneld
      state: stopped
  - name: Stop service kube-nginx
    service:
      name: kube-nginx
      state: stopped                
  - name: delete service
    file:
      path: "{{ item }}"
      state: absent  
    with_items:
      - /lib/systemd/system/kubelet.service 
      - /lib/systemd/system/kube-proxy.service 
      - /lib/systemd/system/flanneld.service 
      - /lib/systemd/system/kube-nginx.service    
      - /etc/systemd/system/docker.service.requires/flanneld.service 
  - name: delete ssl path
    file:
      path: /opt/kubernetes/ssl
      state: absent
  - name: create ssl path    
    file:    
      path: /opt/kubernetes/ssl
      state: directory 
  - name: delete cfg path
    file:
      path: /opt/kubernetes/cfg
      state: absent
  - name: create cfg path    
    file:    
      path: /opt/kubernetes/cfg
      state: directory                               
