# yaml 配置实例
version: '3'
services:
  redis:
    image: redis
    restart: always
    container_name: redis
    command: redis-server --requirepass DotMoo123
    ports:
      - 6379:6379
    volumes:
      - /data/redis/data:/data:rw