apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-uat-exporter
  namespace: pg-uat-exporter
  labels:
    app: postgres
    app.kubernetes.io/name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      app.kubernetes.io/name: postgresql
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/name: postgresql
    spec:
      containers:
      - name: postgres-exporter
        image: wrouesnel/postgres_exporter:latest
        args:
          - "--web.listen-address=:9187"
          - "--log.level=debug"
        env:
          - name: DATA_SOURCE_USER
            valueFrom:
              secretKeyRef:
                name: pg-uat
                key: username
          - name: DATA_SOURCE_PASS
            valueFrom:
              secretKeyRef:
                name: pg-uat
                key: password
          - name: DATA_SOURCE_URI
            value: "x.x.x.x:5432/postgres?sslmode=disable"
        ports:
        - name: http-metrics
          containerPort: 9187        
---
apiVersion: v1
kind: Service
metadata:
  name: pg-uat-exporter
  namespace: monitoring
  labels:
    app: pg-uat-exporter
spec:
  ports:
  - name: port-tcp-9187
    port: 9187
    targetPort: 9187  
  selector:
    app: pg-uat-exporter
  type: ClusterIP