apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: common-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jaeger
  template:
    metadata:
      labels:
        name: jaeger
    spec:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: renv
                operator: In
                values:
                - monitor
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.29
        imagePullPolicy: IfNotPresent
      tolerations:
      - effect: NoSchedule
        key: role
        operator: Equal
        value: service              
      imagePullSecrets:
      - name: 4dtc

---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: jaeger
  name: jaeger
  namespace: common-server
spec:
  type: NodePort
  ports:
  - name: http-16686
    port: 16686
    targetPort: 16686
  - name: http-14250
    port: 14250
    targetPort: 14250
  - name: http-14268
    port: 14268
    targetPort: 14268
  selector:
    name: jaeger
