apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: common-server
data:
  otel-collector-config.yaml: |
  receivers:
    otlp:
      protocols:
        grpc:
        http:
          endpoint: "0.0.0.0:4318"
          cors:
            allowed_origins:
              - http://*
              - https://*
  processors:
    tail_sampling:
      decision_wait: 10s
      num_traces: 100
      expected_new_traces_per_sec: 10
      policies:
        [
            {
              name: policy-latency,
              type: latency,
              latency: {threshold_ms: 5000}
            },
            {
                name: policy-error,
                type: status_code,
                status_code: {status_codes: [ERROR]}
            },
            {
              name: policy-probabilistic,
              type: probabilistic,
              probabilistic: {sampling_percentage: 20}
            }  
          ]
  extensions:
    zpages: {}
    memory_ballast:
      size_mib: 683
  exporters:
    logging:
    otlp:
      endpoint: "http://someotlp.target.com:4317" # Replace with a real endpoint.
      tls:
        insecure: true
    zipkin:
      endpoint: "http://zipkin:9411/api/v2/spans"
      format: proto
    jaeger:
      endpoint: jaeger:14250
      tls:
        insecure: true
  service:
    extensions: [zpages, memory_ballast]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [tail_sampling]
        exporters: [zipkin, jaeger]