apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: common-server
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: renv
                operator: In
                values:
                - monitor
      containers:
      - image: otel/opentelemetry-collector-contrib:0.57.2
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55679 # Default endpoint for ZPages.
        - containerPort: 4317 # Default endpoint for OpenTelemetry grpc receiver.
        - containerPort: 4318 # Default endpoint for OpenTelemetry http receiver.
        - containerPort: 14250 # Default endpoint for Jaeger gRPC receiver.
        - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
        - containerPort: 9411 # Default endpoint for Zipkin receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        volumeMounts:
        - mountPath: /etc/otelcol-contrib
          name: otel-collector-config-vol
      tolerations:
      - effect: NoSchedule
        key: role
        operator: Equal
        value: service    
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: otel-collector-config
            path: config.yaml
          name: otel-collector-config
        name: otel-collector-config-vol
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: common-server
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  selector:
    component: otel-collector