apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-dev
  namespace: common-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-dev
  template:
    metadata:
      labels:
        app: kafka-dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - service
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-dev:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://192.168.21.2:9092
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_HEAP_OPTS
          value: -Xmx2G -Xms2G
        - name: KAFKA_LOG_DIRS
          value: /kafka/logs
        name: kafka-dev
        image: registry.cn-shenzhen.aliyuncs.com/sdtc/kafka:2.12-2.4.1
        imagePullPolicy: IfNotPresent          
        volumeMounts:
        - mountPath: /kafka/logs
          name: volume-data 
      tolerations:
      - effect: NoSchedule
        key: role
        operator: Equal
        value: service                      
      volumes:
      - hostPath:
          path: /logs/common/dev/kafka/data
          type: ""
        name: volume-data                          
      imagePullSecrets:
      - name: 4dtc          
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-dev
  namespace: common-server
  labels:
    app: kafka-dev
spec:
  ports:
  - name: port-tcp-9092
    port: 9092
    nodePort: 9092   
  selector:
    app: kafka-dev
  type: NodePort