apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  namespace: common-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/4d_prom/filebeat:7.17.0
        imagePullPolicy: IfNotPresent
        name: filebeat
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: config
          readOnly: true
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/input/
          name: input
        - mountPath: /logs
          name: logs
          readOnly: true
        - mountPath: /usr/share/filebeat/data/
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /logs/common/filebeat/conf/
          type: ""
        name: config
      - hostPath:
          path: /logs/common/filebeat/conf/input
          type: ""
        name: input
      - hostPath:
          path: /logs/sit/
          type: ""
        name: logs
      - hostPath:
          path: /logs/common/filebeat/data
          type: ""
        name: data
